### ISSUE TITLE
Ubuntu 15.10下播放失败

### ISSUE THREAD

**Issue by lilimo** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#25]
Traceback (most recent call last):
  File "/home/lvguangyan/.local/share/deepin-music-player/plugins/neteasecloudmusic/netease_music_view.py", line 104, in on_music_view_double_click
    self.request_song(song, play=True)
  File "/home/lvguangyan/.local/share/deepin-music-player/plugins/neteasecloudmusic/netease_music_view.py", line 282, in request_song
    url = nplayer.get_songs_url([song['sid']])[0]['url']
  File "/home/lvguangyan/.local/share/deepin-music-player/plugins/neteasecloudmusic/netease_api.py", line 222, in get_songs_url
    if cookie.name == "__csrf":
AttributeError: 'str' object has no attribute 'name'
在终端运行错误代码如上

**Comment by lilimo** [comment]
问题已解决，应该是使用新浪微博登陆的bug，使用网易账号登陆就能正常播放；
当然也有其他可能性，我做了下面这些：
1. 卸载深度音乐，添加noobslab的ppa，update后安装deepin-music，安装它推荐安装的所有包；
2. 重新clone插件，删除.local/share/deepin-music-player/plugins中网易云插件的文件夹、删除.cache/deepin-music-playe中的缓存文件夹；
3. 重新安装网易云音乐插件，并使用新浪微博登陆。

**Comment by lilimo** [comment]
问题已解决，应该是使用新浪微博登陆的bug，使用网易账号登陆就能正常播放；
当然也有其他可能性，我做了下面这些：
1. 卸载深度音乐，添加noobslab的ppa，update后安装deepin-music，安装它推荐安装的所有包；
2. 重新clone插件，删除.local/share/deepin-music-player/plugins中网易云插件的文件夹、删除.cache/deepin-music-playe中的缓存文件夹；
3. 重新安装网易云音乐插件，并使用网易账号登陆。

**Comment by n374** [comment]
50700e518ddac3fe29ec1dade22aa115a428ef15  Fixed

我在网页端测试了下，之前是绑定新浪微博，现在用新浪微博登陆是重新建一个账号。

**Comment by lilimo** [comment]
把你代码替换进去试了一下，还是不行，我的新浪微博是和网易账号绑定的，登陆之后出来的歌单是一样的，但是用新浪微博登陆的就是无法播放，错误信息是一样的。（具体的截图）
![default](https://cloud.githubusercontent.com/assets/18569847/14681575/40b404be-0754-11e6-982a-ce2334300685.png)
![default](https://cloud.githubusercontent.com/assets/18569847/14681577/40d70176-0754-11e6-9e22-055b2bd864ee.png)
![default](https://cloud.githubusercontent.com/assets/18569847/14681576/40d2cc78-0754-11e6-86cf-4405b930e516.png)
![default](https://cloud.githubusercontent.com/assets/18569847/14681613/6edaf4b0-0754-11e6-9862-568daaf20a6c.png)

**Comment by lilimo** [comment]
第一二张是使用网易账号登陆的，正常播放，第三张是使用新浪微博登陆的，无法播放，最后是我修改的代码，虽然不怎么懂python，但应该是不会错的

**Comment by lilimo** [comment]
其实这问题不大，不影响主要功能，但我觉得你最好在Readme里面说明一下，不然下一个用新浪微博登陆的人还是会像我一样装了卸卸了装。

**Comment by n374** [comment]
我用一个这两天才绑定新浪微博的账号试了下，出来的歌单确定和账号登录的歌单一致，可能是我什么时候解绑了吧。

至于你说的无法播放的问题，我装了15.10试了下，能正常播放，未发现问题。
