### ISSUE TITLE
openSUSE13.2下无法启用此插件

### ISSUE THREAD

**Issue by xhmelon** [wu-nerd/dmusic-plugin-NeteaseCloudMusic#3]
KDE，使用的是 Packman 里的软件包（即深度音乐2.0）。
能够在「附加组件」中看到该插件，但无法启用（点击启用按钮无效）。

**Comment by n374** [comment]
在终端运行深度音乐，看看启用插件时有什么错误提示。

**Comment by xhmelon** [comment]
#启动深度音乐

```
thomas@linux-vzqp:~> deepin-music-player
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO     Loading settings...
INFO     Loading application theme...
INFO     Loading MediaDB...
INFO     Initialize Gui...
/usr/lib/python2.7/site-packages/dtk/ui/utils.py:396: PangoWarning: pango_layout_set_markup_with_accel: 第 1 行出错：实体没有以分号结束。很可能您使用了 & 字符而又不是一个实体 - 将这个 & 变为 &amp;
layout.set_markup(text)
INFO     MMKeys mode: None
```

#启用插件

```
Traceback (most recent call last):
  File "/usr/share/deepin-music-player/src/plugins.py", line 119, in enable_plugin
    plugin = self.load_plugin(plugin_name)
  File "/usr/share/deepin-music-player/src/plugins.py", line 81, in load_plugin
    plugin = imp.load_source(plugin_name, os.path.join(path,'__init__.py'))
  File "/home/thomas/.local/share/deepin-music-player/plugins/neteasecloudmusic/__init__.py", line 4, in <module>
    from netease_music_browser import MusicBrowser
  File "/home/thomas/.local/share/deepin-music-player/plugins/neteasecloudmusic/netease_music_browser.py", line 13, in <module>
from netease_music_player import neteasecloud_music_player, player_interface
  File "/home/thomas/.local/share/deepin-music-player/plugins/neteasecloudmusic/netease_music_player.py", line 17, in <module>
from netease_api import NetEase
  File "/home/thomas/.local/share/deepin-music-player/plugins/neteasecloudmusic/netease_api.py", line 34, in <module>
    import requests
ImportError: No module named requests
WARNING  Unable to enable plugin neteasecloudmusic
No module named requests
```

**Comment by n374** [comment]
应该是自带的Python没有requests库
pip install requests
或参照http://docs.python-requests.org/en/latest/user/install/#install
